### ISSUE TITLE
AWS structured stream schema 용도

### ISSUE THREAD

**Issue by dudldude** [swsnu/ds2spring2018#11]
안녕하세요. 
structured stream code를 보면 아래 schema 정의 부분이 있는데, code 상 call 되는 부분이 없는 것 처럼 보입니다. schema 의 용도와 code에서 어떻게 적용되는지 설명 부탁드립니다. 

# Define the relational schema
schema = StructTyStringTypepe().add("title", ()).add("genre", StringType()).add("year", LongType())

감사합니다.

**Comment by DifferentSC** [comment]
Scala로 된 코드지만, from_json()을 활용하여 Kafka스트림을 파싱하는 예제를 참고삼아 보내드립니다.
https://stackoverflow.com/questions/42506801/how-to-use-from-json-with-kafka-connect-0-10-and-spark-structured-streaming

감사합니다.
TA 이계원 드림
