### ISSUE TITLE
HW2에서 voxceleb_main.py 실행시 voxceleb-10-model 폴더가 안생겨요....

### ISSUE THREAD

**Issue by kuck12** [swsnu/ds2spring2018#21]
9조 입니다.

voxceleb_main_local.py  수행시는 voxceleb-10-model 폴더가 잘생기고 파일도 잘생기는건 확인했는데,
voxceleb_main.py 에 15 line을  /home/ubuntu/notebooks/hw2/voxceleb-10-model으로 바꾸고 실행했는데도  voxceleb-10-model 폴더 자체가 안생깁니다. 

도와주세요.... ㅠ

**Comment by gyeongin** [comment]
Job을 실행하신 worker들 중 chief worker가 있는 인스턴스에 해당 체크포인트 디렉토리가 생깁니다. distributed_run.py의 worker list 중 첫 번째가 chief worker이니, 그 ip에 해당하는 인스턴스를 확인해주세요.

**Comment by kuck12** [comment]
말씀해주신대로 다른 서버에 들어있었습니다. 
감사합니다.
